fulll-dbt-profile:
  target: sbx
  outputs:
    sbx:
      type: bigquery
      method: oauth
      project: prj-data-fulll-data-dev-bf85
      execution_project: prj-astrafy-main-courses
      schema: bqdts_sbx
      threads: 12
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
      impersonate_service_account: sa-dbt-fulll-dev@prj-astrafy-main-courses.iam.gserviceaccount.com
    dev:
      type: bigquery
      method: oauth
      project: prj-data-fulll-data-dev-bf85
      execution_project: prj-astrafy-main-courses
      schema: bqdts
      threads: 12
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
      impersonate_service_account: sa-dbt-fulll-dev@prj-astrafy-main-courses.iam.gserviceaccount.com
    prd:
      type: bigquery
      method: oauth
      project: prj-data-fulll-data-prd-f6de
      execution_project: prj-astrafy-main-courses
      schema: bqdts
      threads: 12
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
      impersonate_service_account: sa-dbt-fulll-prd@prj-astrafy-main-courses.iam.gserviceaccount.com

elementary:
  target: default
  outputs:
    default:
      type: bigquery

      ## Service account auth ##
      method: oauth
      impersonate_service_account: sa-dbt-fulll-dev@prj-astrafy-main-courses.iam.gserviceaccount.com

      project: prj-data-fulll-data-dev-bf85
      execution_project: prj-astrafy-main-courses
      dataset: bqdts_elementary
      threads: 12
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1