name: 'jaffle_shop'
version: '1.0.1'

profile: 'sds-dbt-profile'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

clean-targets: # folders to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

require-dbt-version: [">=1.9.0", "<2.0.0"]

flags:
  partial_parse: true
  use_colors: true
  printer_width: 80
  send_anonymous_usage_stats: false
  require_explicit_package_overrides_for_builtin_materializations: false

query-comment:
  comment: "{{ common.query_comment(node) }}"
  job-label: True

vars:
  source_db_main: "prj-data-sds-lz-dev-4542"
  "dbt_date:time_zone": "Europe/Paris"

models:
  jaffle_shop:
    +docs:
      node_color: "#039dfc"
    +persist_docs:
      relation: true
      columns: true
    +tags: jaffle_shop
    staging:
      +materialized: table
      +tags: stg_jaffle_shop
    intermediate:
      +materialized: table
      +tags: int_jaffle_shop
    datamart:
      +materialized: table
      +tags: datamart_jaffle_shop

seeds:
  jaffle_shop:
    +schema: js_mapping
    +tags: jaffle_shop_seed
    +persist_docs:
      relation: true
      columns: true