name: "common"
version: "1.0.1"

profile: "astrafy"

require-dbt-version: [ ">=1.5.0", "<2.0.0" ]

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # folders to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"
