name: ci-dev

on:
  push:
    tags:
      - 'prd-[0-9]+.[0-9]+.[0-9]+'

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: build_and_push
    permissions:
      contents: read
      id-token: write

    env:
      PACKAGE: jaffle_shop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/308265262426/locations/global/workloadIdentityPools/github-pool/providers/main-provider
          service_account: sa-ci-dbt-fulll-prd@prj-astrafy-main-courses.iam.gserviceaccount.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            europe-west1-docker.pkg.dev/prj-astrafy-main-courses/dbt-training/fulll/${{ env.PACKAGE }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PACKAGE=${{ env.PACKAGE }}

